services:
  app:
    build: .
    depends_on:
      - maindb
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=maindb
      - POSTGRES_PORT=5432
      - OPENAI_CHAT_API_KEY=E6p1TBfcETwh1LS3yA6TwrEbVerW6vstgnD3hYdUt0YBf0YHRrB2JQQJ99BFACHYHv6XJ3w3AAAAACOGgZOY
      - OPENAI_CHAT_API_VERSION=2024-12-01-preview
      - OPENAI_CHAT_API_BASE=https://pasqu-mbxvvr59-eastus2.cognitiveservices.azure.com/
      - OPENAI_CHAT_DEPLOYMENT=gpt-4.1
      - OPENAI_EMBEDDING_API_KEY=AwsRTvwdLk24XVKlRT8TPB258rI6PTgQrw0SZXHFLK2EtUj4lCmuJQQJ99BFACYeBjFXJ3w3AAABACOGds1q
      - OPENAI_EMBEDDING_API_BASE=https://qa-interns-openai-inst.openai.azure.com/openai/deployments/1-text-embedding-ada-002/embeddings?api-version=2023-05-15
      - OPENAI_EMBEDDING_API_VERSION=2023-05-15
      - OPENAI_EMBEDDING_DEPLOYMENT=${OPENAI_EMBEDDING_DEPLOYMENT}
      - QTEST_REQUIREMENTS_API_URL=https://sapcoestory.qtestnet.com/api/v3/projects/131167/requirements
      - QTEST_TESTCASES_API_URL=https://sapcoestory.qtestnet.com/api/v3/projects/131167/test-cases
      - QTEST_TESTRUNS_API_URL=https://sapcoestory.qtestnet.com/api/v3/projects/131167/test-runs
      - QTEST_DEFECTS_API_URL=https://sapcoestory.qtestnet.com/api/v3/projects/131167/defects
      - QTEST_API_KEY=93d6be5c-35c1-4115-bf20-62252766f8fe
      - QTEST_REQUIREMENTS_PARENT_ID=11061822
      - QTEST_TESTCASES_PARENT_ID=11061822
      - PYTHONPATH=/app  # Ensure the app directory is in the Python path
    volumes:
      - .:/app
    command: tail -f /dev/null  # Keep the container running for interactive work

  maindb:
    image: pgvector/pgvector:pg17
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume

volumes:
  postgres_data:  # Named volume for persistence
